// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace PeopleTypes
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Building", Namespace = "", IsNullable = false)]
    public partial class TBuilding : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string classNameField;

        private int idField;

        private int typeField;

        private string nameField;

        private TFloor[] floorListField;

        /// <remarks/>
        public string ClassName
        {
            get
            {
                return this.classNameField;
            }
            set
            {
                this.classNameField = value;
                this.RaisePropertyChanged("ClassName");
            }
        }

        /// <remarks/>
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }

        /// <remarks/>
        public int Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Floor")]
        public TFloor[] FloorList
        {
            get
            {
                return this.floorListField;
            }
            set
            {
                this.floorListField = value;
                this.RaisePropertyChanged("FloorList");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TFloor : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string classNameField;

        private int idField;

        private int typeField;

        private string nameField;

        private int numberField;

        private TMan[] peopleField;

        /// <remarks/>
        public string ClassName
        {
            get
            {
                return this.classNameField;
            }
            set
            {
                this.classNameField = value;
                this.RaisePropertyChanged("ClassName");
            }
        }

        /// <remarks/>
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }

        /// <remarks/>
        public int Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }

        /// <remarks/>
        public int Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Man")]
        public TMan[] People
        {
            get
            {
                return this.peopleField;
            }
            set
            {
                this.peopleField = value;
                this.RaisePropertyChanged("People");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TMan : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string classNameField;

        private int idField;

        private int typeField;

        private float pxField;

        private float pyField;

        private float pzField;

        private int colorField;

        private int mobilityField;

        private int ageField;

        private float sizeField;

        private int sexField;

        private int emoStateField;

        private int educLevelField;

        private int roleField;

        private int startRoomField;

        private int startTimeField;

        private int isControlField;

        private int exitIdField;

        /// <remarks/>
        public string ClassName
        {
            get
            {
                return this.classNameField;
            }
            set
            {
                this.classNameField = value;
                this.RaisePropertyChanged("ClassName");
            }
        }

        /// <remarks/>
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }

        /// <remarks/>
        public int Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }

        /// <remarks/>
        public float px
        {
            get
            {
                return this.pxField;
            }
            set
            {
                this.pxField = value;
                this.RaisePropertyChanged("px");
            }
        }

        /// <remarks/>
        public float py
        {
            get
            {
                return this.pyField;
            }
            set
            {
                this.pyField = value;
                this.RaisePropertyChanged("py");
            }
        }

        /// <remarks/>
        public float pz
        {
            get
            {
                return this.pzField;
            }
            set
            {
                this.pzField = value;
                this.RaisePropertyChanged("pz");
            }
        }

        /// <remarks/>
        public int Color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
                this.RaisePropertyChanged("Color");
            }
        }

        /// <remarks/>
        public int Mobility
        {
            get
            {
                return this.mobilityField;
            }
            set
            {
                this.mobilityField = value;
                this.RaisePropertyChanged("Mobility");
            }
        }

        /// <remarks/>
        public int Age
        {
            get
            {
                return this.ageField;
            }
            set
            {
                this.ageField = value;
                this.RaisePropertyChanged("Age");
            }
        }

        /// <remarks/>
        public float Size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }

        /// <remarks/>
        public int Sex
        {
            get
            {
                return this.sexField;
            }
            set
            {
                this.sexField = value;
                this.RaisePropertyChanged("Sex");
            }
        }

        /// <remarks/>
        public int EmoState
        {
            get
            {
                return this.emoStateField;
            }
            set
            {
                this.emoStateField = value;
                this.RaisePropertyChanged("EmoState");
            }
        }

        /// <remarks/>
        public int EducLevel
        {
            get
            {
                return this.educLevelField;
            }
            set
            {
                this.educLevelField = value;
                this.RaisePropertyChanged("EducLevel");
            }
        }

        /// <remarks/>
        public int Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }

        /// <remarks/>
        public int StartRoom
        {
            get
            {
                return this.startRoomField;
            }
            set
            {
                this.startRoomField = value;
                this.RaisePropertyChanged("StartRoom");
            }
        }

        /// <remarks/>
        public int StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
                this.RaisePropertyChanged("StartTime");
            }
        }

        /// <remarks/>
        public int IsControl
        {
            get
            {
                return this.isControlField;
            }
            set
            {
                this.isControlField = value;
                this.RaisePropertyChanged("IsControl");
            }
        }

        /// <remarks/>
        public int ExitId
        {
            get
            {
                return this.exitIdField;
            }
            set
            {
                this.exitIdField = value;
                this.RaisePropertyChanged("ExitId");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
